# **Array Creation**

In [1]:
import numpy as np

In [2]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])

print(a1D)
print(a2D)
print(a3D)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


## 1-d array

In [8]:
a = np.array([127, 128, 129], dtype=np.int8)

print(a)

[ 127 -128 -127]


In [4]:
# np.arange(start, end, step)
# 1차원 배열을 생성한다. range()와 비슷
# create 1-d array. similar to range()
arr1 = np.arange(5)

print(arr1)

[0 1 2 3 4]


In [6]:
arr2 = np.arange(2, 5)

print(arr2)

[2 3 4]


In [7]:
arr3 = np.arange(2, 10, 2)

print(arr3)

[2 4 6 8]


In [10]:
# np.linspace(start, end, number)
# 주어진 범위를 지정한 개수로 나누어 1차원 배열을 생성한다.
# split given range into specified number and create 1-d array.
a = np.linspace(0, 1, 9)

print(a)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


## 2-d array

In [12]:
# np.eye(n, m)
# 2차원 배열을 생성한다.
# create 2-d array.
arr1 = np.eye(3)

print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
arr2 = np.eye(3, 5)

print(arr2)
# 행과 열이 같은 곳은 1 나머지는 0
# if col index equal to row index 1, else 0

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [14]:
# np.diag(array)

arr1 = np.diag([1, 2, 3])

print(arr1)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [15]:
arr2 = np.diag([1, 2, 3], -1)

print(arr2)

[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [16]:
# np.vander(list, n)
# n개의 열을 가진 2차원 배열을 만든다. 마지막 열은 1, 두번째 열은 입력한 리스트가 들어간다. 나머지는 마지막 열과 두번째 열의 비율이 계속 곱해진다.
# create 2-d array has n columns. last column is one and second from last is input list. rest of list filled with value multiflied ratio of last and second value.
arr = np.vander(np.linspace(0, 2, 5), 5)

print(arr)

[[ 0.      0.      0.      0.      1.    ]
 [ 0.0625  0.125   0.25    0.5     1.    ]
 [ 1.      1.      1.      1.      1.    ]
 [ 5.0625  3.375   2.25    1.5     1.    ]
 [16.      8.      4.      2.      1.    ]]


## 3-d array

In [22]:
# np.zeros()
# 0으로 가득 찬 배열을 만든다.
# make array full of 0.
arr1 = np.zeros(3)

print(arr1)

[0. 0. 0.]


In [24]:
arr2 = np.zeros((2, 3))

print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
arr3 = np.zeros((2, 3, 2))

print(arr3)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [26]:
# np.ones()
# 1로 가득찬 배열을 만든다.
# make array full of 1.
arr = np.ones((2,3,2))

print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
