# **Array Index**

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

print(arr[1])
print(arr[-2])
# 1차원 배열의 경우 리스트와 동일하게 인덱싱 할 수 있다. // for 1-d array, can use indexing same with list.

1
8


In [3]:
# 2차원 인덱스
# 2-d index
arr.shape = (2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
print(arr[1, 3])
print(arr[0, -1])
print(arr[0])

8
4
[0 1 2 3 4]


In [5]:
# 슬라이싱
# slicing
arr = np.arange(12)
arr = arr.reshape(3,-1)

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print(arr[:2, 1:3])
# 기본적으로 리스트와 동일하게 슬라이싱 // basically same with list.
# 다차원의 경우 ','를 사용해 구분 // for n-dimension, using ',' for distinguish.

[[1 2]
 [5 6]]


In [7]:
# 정수 배열 인덱싱
# index using integer array
arr = np.arange(10, 0, -1)

print(arr[np.array([3,3,-2,5])])


[7 7 2 5]


In [8]:
 arr = np.arange(25)
 arr.resize(5,5)

 print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [9]:
print(arr[np.array([0, 2]), np.array([3, 2])])
# [0,3]와 [2,2]을 추출 // get [0,2] and [2,2]

[ 3 12]


In [10]:
# Boolean 인덱싱
# boolean indexing
arr = np.array([[1, 2],[np.nan, 4], [5, np.nan]])

print(arr)

[[ 1.  2.]
 [nan  4.]
 [ 5. nan]]


In [11]:
print(arr[~np.isnan(arr)])

[1. 2. 4. 5.]


In [12]:
arr = np.array([15, -1, 9, 4, 7])

print(arr[arr < 9])

[-1  4  7]
