# **ndarray**

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])

print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# np.arange()
# range()와 비슷하게 쓸 수 있다.
# can use similar to range()
arr = np.arange(5)

print(arr)

[0 1 2 3 4]


In [9]:
arr1 = np.arange(1, 5)

print(arr1)

[1 2 3 4]


In [10]:
arr2 = np.arange(2, 10, 2)

print(arr2)

[2 4 6 8]


In [4]:
# np.zeros()
# 0으로 가득찬 배열을 만든다.
# make array full of 0.
arr1 = np.zeros((3,3))

print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
arr2 = np.ones((3,3))

print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# np.empty()
# 빈 값으로 찬 배열을 만든다.
# make array full of empty value.
arr = np.empty((3,3))

print(arr)
# 전에 메모리를 사용한 찌꺼기 데이터가 남아있을 수 있다. // leftover data which used memory before can remain.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# 배열 정보 얻기
# get information of array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int64
