# **Random**

In [2]:
import numpy as np

In [3]:
# np.random.rand()
# 0에서 1사이의 랜덤한 값으로 찬 주어진 형태의 배열을 반환한다. 
# return array of given shape filled with random value between 0 and 1.
a1 = np.random.rand(5)
a2  = np.random.rand(2,3)

print(a1)
print(a2)

[0.56546869 0.98577464 0.85760786 0.80288199 0.66576114]
[[0.58223284 0.88750466 0.036148  ]
 [0.24370437 0.49354387 0.32140345]]


In [4]:
# np.random.randn()
# 표준 정규분포 안의 랜덤한 값으로 찬 주어진 형태의 배열을 반환한다.
# return array of given shape filled with random value in standard normal distribution.
a = np.random.randn(5)

print(a)

[ 1.81402849 -0.90139311  1.03396012  0.71297533  1.13031712]


In [5]:
# np.random.randint()
# 주어진 범위 안에서 임의의 정수를 반환한다.
# return random integer in given range.
n = np.random.randint(5) # 0과 5 사이 // between 0 and 5

print(n)

1


In [7]:
n1 = np.random.randint(-2, 10) # -2에서 10 사이 // between -2 to 10

print(n1)

1


In [8]:
n2 = np.random.randint(-5, 5, size=(2,3), dtype=np.int64)
# 반환되는 형태와 데이터 타입을 지정할 수 있다. // can set shape and dtype to return.

print(n2)

[[-2 -1 -5]
 [-4  2 -2]]


In [3]:
# np.random.choice(1-d array, shape)
# 1차원 배열에서 무작위로 값을 골라 반환한다.
# choose random value in 1-d array and return it.
n = np.random.choice(np.arange(10))

print(n)

2


In [4]:
a = np.random.choice(np.arange(10), (2,3))

print(a)

[[4 0 7]
 [2 1 0]]
