# **Array handling**

In [2]:
import numpy as np

In [3]:
# 배열 정보 얻기
# get information of array
arr = np.eye(5)

print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(5, 5)
2
float64


In [4]:
# 배열 정렬
# sort array
arr = np.array([2, 5, 1, 4])

print(np.sort(arr))

[1 2 4 5]


In [5]:
# 중복된 원소의 제거
# remove duplicate elements
arr = np.array([1, 2, 1, 2, 3, 1, 2, 3, 4, 3, 4, 5])
print(arr)

arr = np.unique(arr)
print(arr)

[1 2 1 2 3 1 2 3 4 3 4 5]
[1 2 3 4 5]


## Reshape

In [6]:
arr = np.arange(10)

print(np.shape(arr))

(10,)


In [7]:
# np.reshape(array, shape), ndarray.reshape(shape)
# 배열을 원하는 형태로 바꾼다.
# change shape of array.
arr1 = np.reshape(arr, (2,5))

print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
arr2 = arr.reshape((2,5))

print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
arr3 = np.reshape(arr, (-1, 2))

print(arr3)
# -1을 사용하면 나머지 값을 자동으로 잡아준다. // using -1 set the other value automatically.

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
# ndarray.shape = shape
arr = np.arange(10)
arr.shape = (2,5)

print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
# np.resize(), ndarray.resize()
arr = np.arange(10)
arr1 = np.resize(arr, (2,5))

print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
arr2 = arr.resize((2,5))

print(arr2)
# reshape와 달리 ndarray.resize()는 값을 반환하지 않는다. // ndarray.resize not return values.

None


In [13]:
arr.resize((2, 5))

print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
arr = np.arange(10)

arr1 = np.resize(arr, (3,3))
print(arr1)
# resize는 reshape와 달리 원소의 개수에 변화가 있어도 자동으로 처리한다. // result of resize can have different number of elements from before not like reshape.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
arr = np.arange(5)

arr2 = np.resize(arr, (3,3))
print(arr2)
# 원소가 부족할 경우 반복 // if element not enough, iter.

[[0 1 2]
 [3 4 0]
 [1 2 3]]


In [16]:
# np.transpose(), ndarray.transpose(), ndarray.T
# 배열의 행과 열을 바꾼다.
# change cols and rows of array.
arr = np.arange(1,10)
arr.resize((3,3))

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr1 = np.transpose(arr)

print(arr1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
arr2 = arr.transpose()

print(arr2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
arr3 = arr.T

print(arr3)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
# ndarray.flatten()
# 배열을 일차원 배열로 만들어 반환한다.
# return 1-d array.
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
arr1 = arr.flatten()

print(arr1)

[1 2 3 4 5 6]


In [22]:
arr2 = arr.flatten('F')

print(arr2)
# 열을 기준으로 정렬한다. // sort values using col.

[1 4 2 5 3 6]


In [23]:
# np.squeeze()
# shape에 1이 있을 경우 1차원을 축소한다.
# reduce 1 dimension, if shape has 1.
arr = np.array([[[1],[2]],[[3],[4]]])
print(arr)
print(arr.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [24]:
arr1 = np.squeeze(arr)

print(arr1)
print(arr1.shape)

[[1 2]
 [3 4]]
(2, 2)


In [25]:
# np.expand_dims()
# 배열의 차원을 확장한다.
# expand dimension of array.
arr = np.array([1,2])

print(arr)
print(arr.shape)

[1 2]
(2,)


In [26]:
arr1 = np.expand_dims(arr, axis=0)
arr2 = np.expand_dims(arr, axis=1)

print(arr1)
print(arr1.shape)
print(arr2)
print(arr2.shape)

[[1 2]]
(1, 2)
[[1]
 [2]]
(2, 1)


## combine

In [27]:
# np.stack()
# 새로운 축을 기준으로 배열을 합친다.
# combine arrays along to new axis.
arr1 = np.zeros(3, dtype=np.uint8)
arr2 = np.ones(3, dtype=np.uint8)
arr3 = np.full(3, 2)

print(arr1)
print(arr2)
print(arr3)
# stack을 사용하려면 shape가 동일해야 한다. // to use stack, shape should be same.

[0 0 0]
[1 1 1]
[2 2 2]


In [28]:
arr = np.stack([arr1, arr2, arr3])

print(arr)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [29]:
arr = np.stack([arr1, arr2, arr3], axis=1)

print(arr)
# 축을 지정할 수 있다. // can set axis.

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [30]:
arr = np.stack([arr1, arr2, arr3], axis=-1)

print(arr)
# -1을 사용하면 마지막 축을 지정한다. // if use -1, set last axis.

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [31]:
# np.vstack()
# 배열을 행 기준으로 결합한다.
# stack array row wise.
arr1 = [1, 1, 1]
arr2 = [2, 2, 2]

arr = np.vstack([arr1, arr2])
print(arr)

[[1 1 1]
 [2 2 2]]


In [32]:
arr1 = np.ones((2,3), dtype=np.uint8)
arr2 = [2, 2, 2]

arr = np.vstack([arr1, arr2])
print(arr)
# 1차원과 2차원 배열도 결합할 수 있다. // can stack 1-d and 2-d arrays.

[[1 1 1]
 [1 1 1]
 [2 2 2]]


In [33]:
# np.hstack()
# 배열을 열 기준으로 결합한다.
# stack array col wise.
arr1 = [1, 1]
arr2 = [2, 2]

arr = np.hstack([arr1, arr2])
print(arr)

[1 1 2 2]


In [34]:
arr1 = [[1, 1], [2, 2]]
arr2 = [[3], [4]]

arr = np.hstack([arr1, arr2])
print(arr)

[[1 1 3]
 [2 2 4]]


In [35]:
# np.dstack()
# 배열을 깊이 방향으로 결합한다.
# stack array depth wise.
arr1 = np.zeros((2,3))
arr2 = np.ones((2,3))

arr = np.dstack([arr1, arr2])
print(arr)
print(arr.shape)

[[[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]]
(2, 3, 2)


In [36]:
arr1 = [1, 1, 1]
arr2 = [2, 2, 2]

arr = np.dstack([arr1, arr2])
print(arr)
print(arr.shape)
# 1차원 배열도 3차원 배열로 합쳐진다. // 1-d array combined be 3-d array.

[[[1 2]
  [1 2]
  [1 2]]]
(1, 3, 2)


In [37]:
# np.concatenate()
# 배열을 하나로 합친다.
# combine arrays.
arr1 = np.zeros((2,3))
arr2 = np.ones((2,3))

arr = np.concatenate([arr1, arr2])
print(arr)
# 같은 차원의 배열만 합칠 수 있다. // can combine same dimension array only.

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
arr = np.concatenate([arr1, arr2], axis=1)

print(arr)
# 축을 지정할 수 있다. // can set axis.
# 결합 축 이외의 형태는 동일해야한다. // shape except axis should be same.

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [39]:
# np.block()
# 형태를 지정해서 배열을 결합한다.
# combine array in given shape.
arr1 = np.zeros((2,3))
arr2 = np.ones((2,3))

print(arr1)
print(arr2)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
arr = np.block([arr1, arr2])

print(arr)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [41]:
arr = np.block([[arr1], [arr2]])

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
arr = np.block([[arr1, arr2], [arr2, arr1]])

print(arr)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [43]:
arr = np.block([[[arr1]], [[arr2]]])

print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [44]:
arr3 = np.arange(6)

arr = np.block([[arr1, arr2], [arr3]])

print(arr)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 1. 2. 3. 4. 5.]]
