# **Numpy Input Output**

In [2]:
import numpy as np

In [3]:
# np.save(file_name, arr)
# 배열을 .npy 파일로 저장한다.
# save array as .npy file.
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
np.save('./test01.npy', a)

In [5]:
# np.savez(file_name, arr...)
# 여러 배열을 하나의 파일로 저장한다. (.npz)
# save several arrays into one file. (.npz)
a1 = np.arange(5)
a2 = np.eye(3,3)

np.savez('./test02.npz', a1, a2)

In [6]:
# np.load(file_name)
# 저장한 배열을 불러온다.
# load saved array.
a_load1 = np.load('./test01.npy')

print(a_load1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
a_load2 = np.load('./test02.npz')

print(a_load2.files)

['arr_0', 'arr_1']


In [8]:
print(a_load2['arr_0'])
print(a_load2['arr_1'])

[0 1 2 3 4]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# np.savetxt()
# 배열을 txt 파일로 저장한다.
# save array as txt file.
a = np.arange(5)

np.savetxt('./test03.txt', a, delimiter=',')

In [10]:
# np.loadtxt()
# txt 파일을 불러온다.
# load txt file.
a = np.loadtxt('./test03.txt', dtype=np.float64, delimiter=',')

print(a)

[0. 1. 2. 3. 4.]


In [11]:
# np.genfromtxt()
# txt 파일을 불러온다. 빈 값에 대해 처리가 가능하다.
# load txt file. can handle empty value.
with open('test04.txt', 'w') as f:
    f.write(
        '''
        1, 2, 3
        4,,6
        7, 8, 9
        '''
    )

In [12]:
a = np.genfromtxt('test04.txt', delimiter=',')

print(a)
# np.load()를 사용할 경우 오류가 발생한다. // error occur if use np.load().

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [13]:
# 이미지 파일 배열로 저장, 불러오기
# save, load image file as array
import cv2
import os

image_gray = cv2.imread('../sample_img.jpg', 0)
image_color = cv2.imread('../sample_img.jpg', 1)

cv2.imshow('gray', image_gray)
cv2.imshow('color', image_color)
cv2.waitKey(0)

-1

In [14]:
np.savez('./image.npz', arr1 = image_gray, arr2 = image_color)
np.savez_compressed('./image_compressed.npz', arr1 = image_gray, arr2 = image_color)

print(os.path.getsize('./image.npz'))
print(os.path.getsize('./image_compressed.npz'))

1440502
1068145


In [15]:
data = np.load('./image_compressed.npz')
result1 = data['arr1']
result2 = data['arr2']

cv2.imshow('result1', result1)
cv2.imshow('result2', result2)
cv2.waitKey(0)

-1